### ISSUE TITLE
Binning Narrowband Images

### ISSUE THREAD

**Issue by danieldh206** [jarmoruuth/AutoIntegrate#33] opened 2023-12-12 16:57 UTC
https://github.com/jarmoruuth/AutoIntegrate/blob/77f26ea4d6ea655a58423dff3190236574b86444/AutoIntegrateEngine.js#L9678C1-L9678C27

When I try to bin SHO narrowband images I keep getting 

> ReferenceError: postfix is not defined

I believe this is because of the _function RGBNB_Channel_Mapping_ does not find RGB channels. 

I am working with QHY600 files that are huge and want to bin them. 

Thank you,
Daniel

**Comment by jarmoruuth** [comment] 2023-12-12 17:19
Hi Daniel,

I was able to reproduce the issue. Function runBinningOnLights references to non-existing variable postfix. If replaced with a call getBinningPostfix() it works fine.

This must be an unfortunate side effect of  changes done for Flowchart. Unfortunately I am in a middle of complicated change to intermediate output image names. They make no sense but are also mixed all over the place so it is messy.  

So I am not sure how quickly I can post a fix. I hope to be done in a few days.

I have done also binning for QHY600 files since they can be really big.

Regards,
Jarmo

**Comment by danieldh206** [comment] 2023-12-12 17:57
Which line in the script can I manually modify the getBinningPostfix() call until you get a fix? 
Thank you,
Daniel

**Comment by jarmoruuth** [comment] 2023-12-12 18:40
My line numbers are changed but you can search function runBinningOnLights in the file AutoIntegrateEngine.js. Line 2000+ something. In the second line in the the function there is call to util.addProcessingStep where you see variable postfix. Just replace postfix with getBinningPostfix().

Jarmo

**Comment by jarmoruuth** [comment] 2023-12-14 21:27
Fix for this is now available in my PixInsight test repository:  https://ruuth.xyz/test/autointegrate/

**Comment by danieldh206** [comment] 2023-12-15 20:27
Just to verify, is v1.6.5.2 test2 the correct version? I had a little difficult trying to get the update from the test repository.

**Comment by jarmoruuth** [comment] 2023-12-15 20:58
Yes, that is the correct version.

Jarmo

**Comment by danieldh206** [comment] 2023-12-15 22:11
I just ran a Ha_LRGB data set through the test version and binning worked correctly! Thank you.

**Comment by jarmoruuth** [comment] 2023-12-16 16:48
Great that you verified it! So this is fixed in v1.65.2.

**Closed by jarmoruuth** 2023-12-16 16:48 UTC
