### ISSUE TITLE
Script Errors in PI (windows)

### ISSUE THREAD

**Issue by dts350z** [jarmoruuth/AutoIntegrate#1] opened 2021-03-23 20:03 UTC
Each time I use the script I see a large block of red error text go by, but it is usually not available to scroll up to by the time the script finishes (successfully).

Sometimes the script doesn't not finish successfully, and I don't know if the two are related or not. 

Here is a fragment from the log showing the "big" error:

Measuring: Y:/AstroPic Services/iTelescope.net/Vela XYZ/Re-Visit Mar 2021/Oiii_MergeMosaic3_cc.xisf
Image Calculations: 9.258 s
     Star Detector: 7.020 s
36430 Star(s) detected
36325 PSF(s) fitted

===== SubframeSelector: 5 succeeded, 0 failed, 0 skipped =====
*** PCL Win32 System Exception: At address 00007FF82F9BF0B7 with exception code C0000005 :
Access violation: invalid memory read operation at address 0000000000000190

*** Backtrace Information ***
================================================================================
  0: KiUserExceptionDispatcher in module: C:\Program Files\PixInsight\bin\PixInsight.exe at address: 0xDB5B0A70
  1: _NLG_Return2 in module: C:\Program Files\PixInsight\bin\VCRUNTIME140_1.dll at address: 0xD2FF1150
  2: _NLG_Return2 in module: C:\Program Files\PixInsight\bin\VCRUNTIME140_1.dll at address: 0xD2FF1150
  3: _NLG_Return2 in module: C:\Program Files\PixInsight\bin\VCRUNTIME140_1.dll at address: 0xD2FF1150
  4: _NLG_Return2 in module: C:\Program Files\PixInsight\bin\VCRUNTIME140_1.dll at address: 0xD2FF1150
  5: _CxxFrameHandler4 in module: C:\Program Files\PixInsight\bin\VCRUNTIME140_1.dll at address: 0xD2FF4040
  6: _chkstk in module: C:\WINDOWS\SYSTEM32\ntdll.dll at address: 0xDB5B1E50
  7: RtlRaiseException in module: C:\WINDOWS\SYSTEM32\ntdll.dll at address: 0xDB561020
  8: KiUserExceptionDispatcher in module: C:\WINDOWS\SYSTEM32\ntdll.dll at address: 0xDB5B0A70
  9: KiUserExceptionDispatcher in module: C:\Program Files\PixInsight\bin\SubframeSelector-pxm.dll at address: 0xDB5B0A70
 10: KiUserExceptionDispatcher in module: C:\Program Files\PixInsight\bin\SubframeSelector-pxm.dll at address: 0xDB5B0A70
================================================================================
<* failed *>
SubframeSelectorMeasure:calculate weight
FWHMMin 1.6562331914901733, EccMin 0.44748353958129883, SNRMin 58.31916427612305
FWHMMax 1.8097585439682007, EccMax 0.6593354344367981, SNRMax 116.19914245605469
AutoIntegrate FWHM 1.705655574798584, Ecc 0.6256239414215088, SNR 69.07122802734375, SSWEIGHT 60.59270007402547, Y:/AstroPic Services/iTelescope.net/Vela XYZ/Re-Visit Mar 2021/Blue_MergeMosaic3_cc.xisf
...
and here is an example of where the script doesn't complete.
...
AutoIntegrate   Using Percentile clip for rejection because number of images is 5

ImageIntegration: Global context
*** Error: FileDataCache::Load(): Corrupted cache data.

Opening files:
...
I tried clearing the cache (both types) in ImageIntegration but it didn't help.

ending with:

AutoIntegrate No ABE for Integration_RGB
AutoIntegrate Color calibration on Integration_RGB_noABE
Error: 

ColorCalibration
Cannot execute instance on view: Integration_RGB_noABE

Reason: ColorCalibration can only be executed on color images.

Processing stopped!
Write processing steps to Y:/AstroPic Services/iTelescope.net/Vela XYZ/Re-Visit Mar 2021/AutoIntegrate.log
...

[AutoIntegrate.log](https://github.com/jarmoruuth/AutoIntegrate/files/6192435/AutoIntegrate.log)

**Comment by jarmoruuth** [comment] 2021-03-23 20:58
Hi and thanks for the feedback. I understood that you had three issues.

1) Access violation error in SubframeSelector unfortunately happens every time. Since I have not seen any other problems with it, and because I have not found a way to fix it, I have just left it there. I think it happens because SubframeSelector fails to initiate screen output or something, and I do not want that to show. But I need to take a look into that soon.

2) Error "Error: FileDataCache::Load(): Corrupted cache data." is new to me. I have not seen it. Unfortunately I have no real idea how to look into it. Googling that error returns some very old results that say "PixInsight installation has been messed for some reason" and suggests reinstalling. Also one recent suggestion was "open the ImageIntegration process, click the wrench at the bottom and then purge the persistent cache". But I guess you already tried that with no help.

3) AutoIntegrate error "Reason: ColorCalibration can only be executed on color images." happens because the script does not understand the files as filter files. So it assumes that they are color files which is incorrect here. This is one of the most common issues, I really should at least detect the problem sooner. I do not have access to iTelescope files although I did get some LRGB files for testing and they worked.

Below is how the script recognizes different files.

1. First script checks if the file has a FILTER keyword that specifies the image as Luminance, Red, Green, Blue, Ha, SII, OIII or Color data. The following FILTER values are recognized: Luminance, Clear, L, Red, R, Green, G, Blue, B, SII, S, Halpha, Ha, H, OIII, O, Color. If there is a FILTER keyword but it is not one of the recognized values, the file is treated as a color file.

2. If the FILTER keyword is not found then files that end with _L, _R, _G, _B, _H, _S, _O or _C are treated as filter files. For example ngc6514_R.fit is treated as a Red filter file.

3. Otherwise files are assumed to be color files.

So you should rename for example Blue_MergeMosaic3.xisf to Blue_MergeMosaic3_R.xisf. But since you have .xisf files, maybe they are already aligned and stacked? If that is the case then you should actually rename Blue_MergeMosaic3.xisf to Integration_R.xisf (the same for other files), load them into Pixinsight and run the script with AutoContinue button.

I see that you have both RGB and HO files. Then you should also set some mapping for RGB and HO files. I am actually working on some new options in narrowband mapping to RGB but that is still ongoing.

Jarmo

**Comment by dts350z** [comment] 2021-03-23 22:19
Jarmo,

Thanks for getting back to me and thanks so much for writing this script.
Really AWESOME!

In this particular case yes I was using already stacked and integrated
files that were a 4 frame mosaic. The inputs were the merged mosaic
integrated frames, RGB for stars, and Ha and Oiii for the nebula. So I was
using max(RGB,HOO). I see now I need to rename the files, for autointigrate
to understand the filters, and was able to make progress with that, so
again, thanks.

However I also tried to use the script for just the Ha and Oiii, with the
HOO palette, the script stopped with:

AutoIntegrate Could not find image window Integration_S that is needed for
PixelMath mapping

Error: Could not find image window Integration_S that is needed for
PixelMath mapping

Processing stopped!

Write processing steps to Y:/AstroPic Services/iTelescope.net/Vela
XYZ/Re-Visit Mar 2021/AutoIntegrate.log


That log attached.


Glenn

**Comment by jarmoruuth** [comment] 2021-03-23 22:42
Hi @dts350z,

Weird that you got error "Error: Could not find image window Integration_S" with HOO mapping. I just tried it with only Integration_H and Integration_O files and it worked. I tried both Run and AutoContinue buttons. If you can reproduce the problem maybe you could send me AutoIntegrate.log/AutoContinue.log file and I can check it.

Jarmo

**Comment by jarmoruuth** [comment] 2021-03-24 15:49
I created two separate issues for SubframeSelector and filter detection so closing this one.

**Comment by jarmoruuth** [comment] 2021-03-24 15:49
I created two separate issues for SubframeSelector and filter detection so closing this one.

**Closed by jarmoruuth** 2021-03-24 15:49 UTC
